version: "3"

services:
  kms:
    container_name: local-kms-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/github.com/mnPanicMeli/local-kms
      - ./init:/init
      - ./data:/data
    ports:
      - 4566:8080
      - 4599:8080
